### ISSUE TITLE
white screen after changes

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#205]
On windows, when I make changes to my protocol now (registry, forms, or interfaces), I get this error:

```
fs.js:646 Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\protocol.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:510:29)
    at loadProtocolData (http://localhost:3003/static/js/bundle.js:152976:63)
    at http://localhost:3003/static/js/bundle.js:149926:97
    at http://localhost:3003/static/js/bundle.js:108677:18
    at dispatch (http://localhost:3003/static/js/bundle.js:109094:18)
    at http://localhost:3003/static/js/bundle.js:149941:7
    at <anonymous>
fs.openSync @ fs.js:646
module.(anonymous function) @ ELECTRON_ASAR.js:172
fs.readFileSync @ fs.js:551
fs.readFileSync @ ELECTRON_ASAR.js:510
loadProtocolData @ loadProtocolData.js:10
(anonymous) @ file.js:74
(anonymous) @ index.js:8
dispatch @ applyMiddleware.js:35
(anonymous) @ file.js:90
Promise resolved (async)
(anonymous) @ file.js:87
(anonymous) @ index.js:8
(anonymous) @ bindActionCreators.js:3
(anonymous) @ ProtocolLoader.js:31
callCallback @ react-dom.development.js:10878
commitUpdateQueue @ react-dom.development.js:10911
commitLifeCycles @ react-dom.development.js:14377
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
requestWork @ react-dom.development.js:16354
scheduleWork$1 @ react-dom.development.js:16218
enqueueSetState @ react-dom.development.js:11299
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:270
(anonymous) @ Router.js:70
listener @ createTransitionManager.js:54
(anonymous) @ createTransitionManager.js:73
notifyListeners @ createTransitionManager.js:72
setState @ createBrowserHistory.js:95
(anonymous) @ createBrowserHistory.js:120
confirmTransitionTo @ createTransitionManager.js:44
handlePop @ createBrowserHistory.js:118
handlePopState @ createBrowserHistory.js:102
```

And then this white screen:
![white screen](https://user-images.githubusercontent.com/16093053/43975868-01246cc6-9cad-11e8-8f08-6d3a5bddedd4.png)

There is no option to save, though I can navigate back to the main welcome screen and open a protocol again. A protocol file named "C:" shows in the recent list. My changes are lost.

**Comment by jthrilly** [comment]
There's a fix for this in 
https://github.com/codaco/Architect/pull/206

Essentially, it is caused by changes to the protocol route styling. My fix was to revert those changes, but this might be optimal. @wwqrd - can you take a look?
